// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxhzsddelypedukogtnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4aHpzZGRlbHlwZWR1a29ndG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODU1NjgsImV4cCI6MjA2MTk2MTU2OH0.X4t3FrB4IpOdAyandT6d7cLJ9L7ouWJCxPC1PklOgi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);